version: "3.4"
services:
  mariadb:
    hostname: sicredi_db
    container_name: sicredi
    image: mariadb:10
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sicredi
      MYSQL_USER: sicredi_user
      MYSQL_PASSWORD: sicredi_psw
      MYSQL_ROOT_PASSWORD: sicredi_psw
    logging:
      driver: "json-file"
      options:
        max-size: 500m